export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-indigo-deep px-8 py-12 md:px-16">
      <div className="mx-auto max-w-2xl font-body text-sm leading-relaxed text-indigo-border">
        <h1 className="font-display text-3xl font-semibold text-paper">Privacy Policy</h1>
        <p className="mt-2 text-xs text-marigold">
          Draft template — have a qualified lawyer review this before going live.
        </p>
        <p className="mt-6">Last updated: [DATE]</p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">1. What we collect</h2>
        <p className="mt-2">
          We collect information you provide directly: name, email, phone number, address,
          and payment-related metadata (not full card numbers — those go directly to
          Razorpay). We also collect data generated by using the platform: demands, bids,
          orders, reviews, and messages.
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">2. How we use it</h2>
        <p className="mt-2">
          To operate the marketplace (matching buyers and sellers, processing payments,
          enabling delivery), to communicate with you about your orders, and to comply
          with legal obligations (such as GST and income tax record-keeping).
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">3. Who we share it with</h2>
        <p className="mt-2">
          With the other party in a transaction (e.g., your delivery address is shared
          with the seller fulfilling your order), with our payment processor (Razorpay),
          and with our delivery-routing provider (OpenRouteService, which receives only
          coordinates, not your name). We do not sell your personal data to third parties.
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">4. Your rights (DPDP Act, 2023)</h2>
        <p className="mt-2">
          Under India&apos;s Digital Personal Data Protection Act, you have the right to
          access, correct, and request deletion of your personal data, and to withdraw
          consent for its processing. Contact us at [SUPPORT EMAIL] to exercise these rights.
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">5. Data retention</h2>
        <p className="mt-2">
          We retain transaction records as required for tax and audit purposes. Account
          data is retained while your account is active and for a reasonable period after
          closure to resolve disputes or comply with law.
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">6. Security</h2>
        <p className="mt-2">
          We use industry-standard practices including password hashing, encrypted
          connections, and access controls. No system is perfectly secure, and we
          encourage you to use a strong, unique password.
        </p>

        <h2 className="mt-8 font-display text-lg font-semibold text-paper">7. Contact</h2>
        <p className="mt-2">Questions about this policy: [SUPPORT EMAIL]</p>
      </div>
    </div>
  );
}
